import getpass
import logging
import re
import shutil
import sqlite3
import json
import subprocess
import signal
import os
from pathlib import Path
from datetime import datetime, timezone
from fastapi import FastAPI, Query, HTTPException, Request, WebSocket
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
from contextlib import asynccontextmanager

from webapp.api.debug import router as debug_router
from webapp.ws.events import hub as ws_hub, start_forwarding

app = FastAPI(title="warDrive Explorer")

# ── CORS: allow LAN access so mobile devices can reach the UI ─────────────────
# No auth, LAN-only deployment — allow all origins. If the Pi AP is the only
# uplink, only devices on the AP subnet can reach port 8000 anyway.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["GET", "POST", "DELETE"],
    allow_headers=["Content-Type", "Authorization"],
)

app.include_router(debug_router)

# ── Session name validation ───────────────────────────────────────────────────
# Session IDs are generated by wardrive.sh as <TIMESTAMP>_<LABEL> and contain
# only alphanumeric characters, underscores, and hyphens.
_SESSION_RE = re.compile(r'^[A-Za-z0-9_\-]{1,128}$')

def _validate_session(session: str | None) -> str | None:
    """Return session if it is a valid session identifier, else raise HTTPException."""
    if session is None or session == "":
        return None
    if not _SESSION_RE.match(session):
        raise HTTPException(status_code=400, detail="Invalid session identifier")
    return session

def _get_config_value(key: str) -> str | None:
    """Read a single variable from wardrive.conf. Returns None if absent or blank."""
    if not CONFIG_PATH.exists():
        return None
    try:
        with open(CONFIG_PATH) as f:
            for line in f:
                line = line.strip()
                if line.startswith(f"{key}="):
                    val = line[len(key) + 1:].strip('"').strip("'")
                    return val if val else None
    except Exception:
        return None
    return None

def _get_capture_raw_dir() -> Path:
    """Return the configured capture/raw directory, falling back to project default."""
    base = _get_config_value("CAPTURE_BASE_DIR")
    if base:
        return Path(base) / "raw"
    return PROJECT_ROOT / "capture" / "raw"

def _dir_size_bytes(path: Path) -> int:
    """Return total byte size of all files under path."""
    total = 0
    try:
        for p in path.rglob("*"):
            if p.is_file():
                try:
                    total += p.stat().st_size
                except OSError:
                    pass
    except Exception:
        pass
    return total

WEBAPP_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = WEBAPP_ROOT.parent
DB_PATH = PROJECT_ROOT / "processing" / "wardrive.db"
CONFIG_PATH = PROJECT_ROOT / "config" / "wardrive.conf"
# PID file is written by wardrive.sh to the project-local capture/ directory,
# not /tmp, to prevent world-writable /tmp from being a privilege-escalation
# staging area (see wardrive.sh for rationale).
WARDRIVE_PID_FILE = PROJECT_ROOT / "capture" / "wardrive.pid"

@asynccontextmanager
async def lifespan(app):
    print(f"[SYSTEM] Starting warDrive Explorer")
    print(f"[SYSTEM] DB Path: {DB_PATH}")
    print(f"[SYSTEM] DB Exists: {DB_PATH.exists()}")

    if DB_PATH.exists():
        try:
            with sqlite3.connect(str(DB_PATH)) as db:
                count = db.execute("SELECT COUNT(*) FROM bt_devices").fetchone()[0]
                print(f"[SYSTEM] bt_devices count: {count}")
                print(f"[SYSTEM] Loaded Routes: {[r.path for r in app.routes if hasattr(r, 'methods')]}")
        except Exception as e:
            print(f"[SYSTEM] Error checking DB: {e}")

    await start_forwarding()
    yield

app.router.lifespan_context = lifespan
app.mount("/static", StaticFiles(directory=str(WEBAPP_ROOT / "static")), name="static")

@app.get("/")
async def index():
    return FileResponse(WEBAPP_ROOT / "templates" / "index.html")

@app.get("/map")
async def map_page():
    return FileResponse(WEBAPP_ROOT / "templates" / "map.html")

@app.get("/analytics")
async def analytics():
    return FileResponse(WEBAPP_ROOT / "templates" / "analytics.html")

@app.get("/dashboard")
async def dashboard():
    return FileResponse(WEBAPP_ROOT / "templates" / "dashboard.html")

@app.get("/report")
async def report_page():
    return FileResponse(WEBAPP_ROOT / "templates" / "report.html")

@app.get("/storage")
async def storage_page():
    return FileResponse(WEBAPP_ROOT / "templates" / "storage.html")

def _get_ble_gps_positions(session_id=None):
    capture_raw = _get_capture_raw_dir()
    best = {}
    if not capture_raw.exists():
        return best
    if session_id:
        # Resolve the path and ensure it stays inside capture/raw (path traversal guard)
        target = (capture_raw / session_id).resolve()
        if not str(target).startswith(str(capture_raw.resolve())):
            return best
        dirs = [target]
    else:
        dirs = sorted(capture_raw.iterdir(), reverse=True)
    for d in dirs:
        if not (isinstance(d, Path) and d.is_dir()):
            continue
        ndjson = d / "bt" / "esp32_ble.ndjson"
        if not ndjson.exists():
            continue
        with open(ndjson) as f:
            for line in f:
                try:
                    obj = json.loads(line)
                    addr = obj.get("addr")
                    if not addr or "lat" not in obj or "lon" not in obj:
                        continue
                    rssi = obj.get("rssi", -100)
                    if addr not in best or rssi > best[addr]["rssi_dbm"]:
                        best[addr] = {
                            "lat": obj["lat"], "lon": obj["lon"],
                            "rssi_dbm": rssi,
                            "name": obj.get("name") or obj.get("local_name"),
                        }
                except Exception:
                    pass
    return best


@app.get("/api/status")
async def get_db_status():
    if not DB_PATH.exists():
        return {"status": "db_not_found", "message": "Database not found"}
    try:
        with sqlite3.connect(str(DB_PATH)) as db:
            # Only query the specific tables the app uses — don't expose the
            # full schema via sqlite_master (information disclosure).
            _KNOWN_TABLES = ["bt_devices", "wifi_aps", "wifi_clients", "rf_devices"]
            counts = {}
            for table in _KNOWN_TABLES:
                try:
                    # Table names are from a hardcoded whitelist — safe to interpolate.
                    count = db.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
                    counts[table] = count
                except Exception:
                    counts[table] = 0

            return {"status": "connected", "counts": counts}
    except Exception as e:
        logging.error(f"DB status check failed: {e}")
        return {"status": "error", "message": "Database error"}

@app.get("/api/collectors/status")
async def get_collectors_status():
    """Get status of all collectors (wifi, sdr, esp32, gps) and wardrive session."""

    def is_process_running(pgrep_pattern):
        """Check if process matching pattern is running via pgrep."""
        try:
            result = subprocess.run(
                ["pgrep", "-f", pgrep_pattern],
                capture_output=True,
                timeout=2
            )
            return result.returncode == 0
        except Exception:
            return False

    def is_sudo_available():
        """Check if sudoers is configured for wardrive."""
        try:
            result = subprocess.run(
                ["sudo", "-n", "-l", str(PROJECT_ROOT / "wardrive.sh")],
                capture_output=True,
                timeout=2
            )
            return result.returncode == 0
        except Exception:
            return False

    def get_active_session():
        """Find the most recent session without ended_at_utc."""
        capture_raw = _get_capture_raw_dir()
        if not capture_raw.exists():
            return None, None

        for session_dir in sorted(capture_raw.iterdir(), reverse=True):
            if not session_dir.is_dir():
                continue
            manifest = session_dir / "manifest.json"
            if manifest.exists():
                try:
                    with open(manifest) as f:
                        data = json.load(f)
                        if "ended_at_utc" not in data:
                            return data, data.get("session_id")
                except Exception:
                    pass
        return None, None

    def get_collector_enabled_status(manifest_data):
        """Get enabled status from manifest or config file."""
        collectors_enabled = {"wifi": False, "sdr": False, "esp32": False, "gps": False}

        if manifest_data and "collectors" in manifest_data:
            collectors_enabled.update(manifest_data["collectors"])
        else:
            config_path = PROJECT_ROOT / "config" / "wardrive.conf"
            if config_path.exists():
                try:
                    with open(config_path) as f:
                        for line in f:
                            if "ENABLE_WIFI=" in line and "true" in line:
                                collectors_enabled["wifi"] = True
                            elif "ENABLE_SDR=" in line and "true" in line:
                                collectors_enabled["sdr"] = True
                            elif "ENABLE_ESP32=" in line and "true" in line:
                                collectors_enabled["esp32"] = True
                            elif "ENABLE_GPS=" in line and "true" in line:
                                collectors_enabled["gps"] = True
                except Exception:
                    pass

        return collectors_enabled

    # Check if wardrive is running
    wardrive_running = False
    wardrive_pid = None
    if WARDRIVE_PID_FILE.exists():
        try:
            wardrive_pid = int(WARDRIVE_PID_FILE.read_text().strip())
            os.kill(wardrive_pid, 0)
            wardrive_running = True
        except (OSError, ValueError):
            WARDRIVE_PID_FILE.unlink(missing_ok=True)

    # Get active session
    manifest_data, session_id = get_active_session()
    started_at = manifest_data.get("started_at_utc") if manifest_data else None

    # Get enabled status
    collectors_enabled = get_collector_enabled_status(manifest_data)

    # Check each collector
    collectors = {
        "wifi": {
            "enabled": collectors_enabled["wifi"],
            "running": is_process_running("kismet") if collectors_enabled["wifi"] else False
        },
        "sdr": {
            "enabled": collectors_enabled["sdr"],
            "running": is_process_running("rtl_433") if collectors_enabled["sdr"] else False
        },
        "esp32": {
            "enabled": collectors_enabled["esp32"],
            "running": is_process_running("esp32_reader\\.py") if collectors_enabled["esp32"] else False
        },
        "gps": {
            "enabled": collectors_enabled["gps"],
            "running": is_process_running("gpspipe") if collectors_enabled["gps"] else False
        }
    }

    return {
        "wardrive_running": wardrive_running,
        "wardrive_pid": wardrive_pid,
        "session_id": session_id,
        "started_at_utc": started_at,
        "collectors": collectors,
        "sudo_available": is_sudo_available(),
        "timestamp": datetime.now(timezone.utc).isoformat()
    }

@app.post("/api/collectors/start")
async def start_collectors():
    """Start wardrive.sh session. Requires sudoers configuration."""

    # Check if already running
    if WARDRIVE_PID_FILE.exists():
        try:
            pid = int(WARDRIVE_PID_FILE.read_text().strip())
            os.kill(pid, 0)
            if _pid_is_wardrive(pid):
                return {"status": "already_running", "pid": pid}
        except (OSError, ValueError):
            pass
        WARDRIVE_PID_FILE.unlink(missing_ok=True)

    # Check sudo availability
    check = subprocess.run(
        ["sudo", "-n", "-l", str(PROJECT_ROOT / "wardrive.sh")],
        capture_output=True,
        timeout=2
    )
    if check.returncode != 0:
        return {
            "status": "sudo_not_configured",
            "message": "wardrive.sh requires root privileges. Configure sudoers to enable start from the UI.",
            "sudoers_snippet": _sudoers_snippet(),
        }

    # Launch wardrive.sh
    try:
        proc = subprocess.Popen(
            ["sudo", "-n", str(PROJECT_ROOT / "wardrive.sh")],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True
        )
        return {"status": "started", "pid": proc.pid}
    except Exception as e:
        logging.error(f"Failed to start collectors: {e}")
        return {"status": "error", "message": str(e)}

def _sudoers_snippet() -> str:
    user = getpass.getuser()
    script = PROJECT_ROOT / "wardrive.sh"
    return (
        f"# Allow warDrive webapp to start/stop capture sessions\n"
        f"{user} ALL=(root) NOPASSWD: {script}\n"
        f"{user} ALL=(root) NOPASSWD: /usr/bin/kill\n"
    )

def _pid_is_wardrive(pid: int) -> bool:
    """Verify that `pid` is a wardrive.sh bash process.

    Reads /proc/<pid>/cmdline and checks that the command looks like a bash
    script running wardrive.sh.  This prevents the /tmp/wardrive.pid race:
    an attacker who replaces the PID file contents with a sensitive process's
    PID would have to also control that process's cmdline, which they can't.
    """
    try:
        cmdline_path = Path(f"/proc/{pid}/cmdline")
        cmdline = cmdline_path.read_bytes().replace(b'\x00', b' ').decode(errors='replace')
        return "wardrive.sh" in cmdline or "wardrive" in cmdline.lower()
    except Exception:
        return False


@app.post("/api/collectors/stop")
async def stop_collectors():
    """Stop wardrive.sh session. Requires PID file or sudoers for kill."""

    if not WARDRIVE_PID_FILE.exists():
        return {"status": "not_running"}

    try:
        pid = int(WARDRIVE_PID_FILE.read_text().strip())
    except ValueError:
        WARDRIVE_PID_FILE.unlink(missing_ok=True)
        return {"status": "not_running"}

    # Verify process is alive
    try:
        os.kill(pid, 0)
    except OSError:
        WARDRIVE_PID_FILE.unlink(missing_ok=True)
        return {"status": "not_running"}

    # Guard against PID-file tampering: only signal a process that is
    # actually wardrive.sh (checked via /proc/<pid>/cmdline).
    if not _pid_is_wardrive(pid):
        logging.warning(f"PID file contains {pid} but process does not appear to be wardrive.sh — refusing to signal")
        WARDRIVE_PID_FILE.unlink(missing_ok=True)
        return {"status": "not_running"}

    # Try direct SIGTERM first
    try:
        os.kill(pid, signal.SIGTERM)
        return {"status": "stopped"}
    except PermissionError:
        pass

    # Fallback: sudo kill
    try:
        result = subprocess.run(
            ["sudo", "-n", "kill", "-TERM", str(pid)],
            capture_output=True,
            timeout=2
        )
        if result.returncode == 0:
            return {"status": "stopped"}
    except Exception:
        pass

    return {
        "status": "sudo_required_for_kill",
        "message": "Cannot signal root-owned process. Configure sudoers to enable kill from the UI.",
        "sudoers_snippet": _sudoers_snippet(),
    }

@app.get("/api/sessions")
async def get_sessions():
    if not DB_PATH.exists():
        return {"error": "Database not found"}

    try:
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row
            # Fetch all sessions with aggregated counts from observation tables
            query = """
            SELECT
                s.session_id,
                s.started_at_utc,
                s.ended_at_utc,
                (SELECT COUNT(DISTINCT bssid) FROM wifi_obs WHERE session_id = s.session_id) as ap_count,
                (SELECT COUNT(DISTINCT address) FROM bt_obs WHERE session_id = s.session_id) as bt_count,
                (SELECT COUNT(DISTINCT device_id) FROM rf_obs WHERE session_id = s.session_id) as rf_count
            FROM sessions s
            ORDER BY s.started_at_utc DESC
            """
            rows = db.execute(query).fetchall()
            return [dict(row) for row in rows]
    except Exception as e:
        logging.error(f"Database error in get_sessions: {e}")
        return {"error": "Database error"}

@app.get("/api/devices")
async def get_devices(
    table: str = "bt_devices",
    vendor: str = None,
    rssi: float = None,
    date: str = None,
    session: str = None,
    device_type: str = None,
    limit: int = 500,
    offset: int = 0
):
    session = _validate_session(session)
    allowed_tables = ["bt_devices", "wifi_aps", "wifi_clients", "rf_devices"]
    if table not in allowed_tables:
        return {"error": f"Invalid table. Must be one of {allowed_tables}"}

    if not DB_PATH.exists():
        return {"error": "Database not found"}

    # Clamp limit to reasonable value
    limit = min(int(limit), 1000)
    offset = max(int(offset), 0)

    # Table-specific column mappings
    table_schemas = {
        "bt_devices": {
            "primary_key": "address",
            "signal_column": "max_rssi_dbm",
            "vendor_column": "manufacturer",
            "first_seen": "first_seen_utc",
            "last_seen": "last_seen_utc",
            "obs_table": "bt_obs",
            "obs_key": "address",
        },
        "wifi_aps": {
            "primary_key": "bssid",
            "signal_column": "max_signal_dbm",
            "vendor_column": "manufacturer",
            "first_seen": "first_seen_utc",
            "last_seen": "last_seen_utc",
            "obs_table": "wifi_obs",
            "obs_key": "bssid",
        },
        "wifi_clients": {
            "primary_key": "mac",
            "signal_column": None,  # no signal column
            "vendor_column": "manufacturer",
            "first_seen": "first_seen_utc",
            "last_seen": "last_seen_utc",
            "obs_table": "wifi_obs",
            "obs_key": "client_mac",
        },
        "rf_devices": {
            "primary_key": "device_id",
            "signal_column": None,
            "vendor_column": None,
            "first_seen": "first_seen_utc",
            "last_seen": "last_seen_utc",
            "obs_table": "rf_obs",
            "obs_key": "device_id",
        },
    }

    schema = table_schemas.get(table)
    if not schema:
        return {"error": f"Unknown table schema: {table}"}

    try:
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row
            # Safe: table name is validated against whitelist above
            query = f"SELECT * FROM {table}"
            conditions = []
            params = []

            # Session filter (via observation table subquery)
            if session:
                obs_table = schema["obs_table"]
                obs_key = schema["obs_key"]
                pk_column = schema["primary_key"]
                conditions.append(f"{pk_column} IN (SELECT DISTINCT {obs_key} FROM {obs_table} WHERE session_id = ?)")
                params.append(session)

            # Vendor filter (only if table has vendor column)
            if vendor and schema["vendor_column"]:
                conditions.append(f"{schema['vendor_column']} LIKE ?")
                params.append(f"%{vendor}%")

            # RSSI filter (only if table has signal column)
            if rssi is not None and schema["signal_column"]:
                try:
                    rssi = float(rssi)
                    conditions.append(f"{schema['signal_column']} <= ?")
                    params.append(rssi)
                except ValueError:
                    pass

            # Date filter (works on all tables)
            if date:
                try:
                    datetime.strptime(date, "%Y-%m-%d")  # rejects invalid calendar dates
                    conditions.append(f"{schema['first_seen']} >= ?")
                    params.append(f"{date} 00:00:00")
                except ValueError:
                    pass

            # Device type filter (works on tables with device_type column)
            if device_type:
                conditions.append("device_type = ?")
                params.append(device_type)

            if conditions:
                query += " WHERE " + " AND ".join(conditions)

            # Sort by signal if available, otherwise by last seen
            if schema["signal_column"]:
                query += f" ORDER BY {schema['signal_column']} DESC"
            else:
                query += f" ORDER BY {schema['last_seen']} DESC"

            query += " LIMIT ? OFFSET ?"
            params.extend([limit, offset])

            rows = db.execute(query, params).fetchall()
            return [dict(row) for row in rows]
    except Exception as e:
        logging.error(f"Database error in get_devices: {e}")
        return {"error": "Database error"}

@app.get("/api/map/devices")
async def get_map_devices(session: str = None):
    session = _validate_session(session)
    devices = []

    # BLE from raw NDJSON
    ble_positions = _get_ble_gps_positions(session)
    if ble_positions and DB_PATH.exists():
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row
            if session:
                rows = db.execute(
                    "SELECT d.* FROM bt_devices d "
                    "WHERE d.address IN (SELECT DISTINCT address FROM bt_obs WHERE session_id=?)",
                    (session,)
                ).fetchall()
            else:
                rows = db.execute("SELECT * FROM bt_devices").fetchall()
            for row in rows:
                r = dict(row)
                pos = ble_positions.get(r["address"])
                if pos:
                    devices.append({
                        "type": "ble",
                        "address": r["address"],
                        "name": r.get("name"),
                        "manufacturer": r.get("manufacturer"),
                        "device_type": r.get("device_type"),
                        "lat": pos["lat"], "lon": pos["lon"],
                        "rssi_dbm": r.get("max_rssi_dbm") or pos["rssi_dbm"],
                    })

    # WiFi from DB (GPS observations + wigle coords)
    if DB_PATH.exists():
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row
            # Query WiFi observations with GPS data
            if session:
                rows = db.execute("""
                    SELECT DISTINCT w.bssid, a.ssid, a.manufacturer, a.device_type, a.alpr_source,
                           AVG(w.lat) as lat, AVG(w.lon) as lon, MAX(w.signal_dbm) as signal_dbm
                    FROM wifi_obs w
                    JOIN wifi_aps a ON w.bssid = a.bssid
                    WHERE w.session_id = ? AND w.lat IS NOT NULL AND w.lon IS NOT NULL
                    GROUP BY w.bssid
                """, (session,)).fetchall()
            else:
                rows = db.execute("""
                    SELECT DISTINCT w.bssid, a.ssid, a.manufacturer, a.device_type, a.alpr_source,
                           AVG(w.lat) as lat, AVG(w.lon) as lon, MAX(w.signal_dbm) as signal_dbm
                    FROM wifi_obs w
                    JOIN wifi_aps a ON w.bssid = a.bssid
                    WHERE w.lat IS NOT NULL AND w.lon IS NOT NULL
                    GROUP BY w.bssid
                """).fetchall()
            for row in rows:
                r = dict(row)
                devices.append({
                    "type": "wifi",
                    "address": r["bssid"],
                    "name": r.get("ssid"),
                    "manufacturer": r.get("manufacturer"),
                    "device_type": r.get("device_type"),
                    "alpr_source": r.get("alpr_source"),
                    "lat": r["lat"], "lon": r["lon"],
                    "rssi_dbm": r.get("signal_dbm"),
                })

    # RF from DB (GPS observations)
    if DB_PATH.exists():
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row
            if session:
                rows = db.execute("""
                    SELECT DISTINCT r.device_id, d.model, d.device_type,
                           AVG(r.lat) as lat, AVG(r.lon) as lon
                    FROM rf_obs r
                    JOIN rf_devices d ON r.device_id = d.device_id
                    WHERE r.session_id = ? AND r.lat IS NOT NULL AND r.lon IS NOT NULL
                    GROUP BY r.device_id
                """, (session,)).fetchall()
            else:
                rows = db.execute("""
                    SELECT DISTINCT r.device_id, d.model, d.device_type,
                           AVG(r.lat) as lat, AVG(r.lon) as lon
                    FROM rf_obs r
                    JOIN rf_devices d ON r.device_id = d.device_id
                    WHERE r.lat IS NOT NULL AND r.lon IS NOT NULL
                    GROUP BY r.device_id
                """).fetchall()
            for row in rows:
                r = dict(row)
                devices.append({
                    "type": "rf",
                    "address": r["device_id"],
                    "name": r.get("model"),
                    "manufacturer": None,
                    "device_type": r.get("device_type"),
                    "lat": r["lat"], "lon": r["lon"],
                    "rssi_dbm": None,
                })

    return devices


@app.get("/api/map/track")
async def get_map_track(session: str = None):
    session = _validate_session(session)
    capture_raw = _get_capture_raw_dir()
    points = []
    if not capture_raw.exists():
        return points

    dirs = []
    if session:
        # Resolve path and ensure it stays inside capture/raw (path traversal guard)
        d = (capture_raw / session).resolve()
        if str(d).startswith(str(capture_raw.resolve())) and d.is_dir():
            dirs = [d]
    else:
        dirs = sorted(capture_raw.iterdir(), reverse=True)

    def nmea_to_dd(coord, hemi):
        if not coord or "." not in coord:
            return None
        dot = coord.index(".")
        deg = int(coord[:dot-2])
        minutes = float(coord[dot-2:])
        dd = deg + minutes / 60.0
        if hemi in ("S", "W"):
            dd = -dd
        return round(dd, 7)

    for d in dirs:
        if not (isinstance(d, Path) and d.is_dir()):
            continue
        nmea_log = d / "gps" / "nmea.log"
        if not nmea_log.exists():
            continue
        with open(nmea_log, errors="replace") as f:
            for line in f:
                line = line.strip()
                if not (line.startswith("$GPRMC") or line.startswith("$GNRMC")):
                    continue
                parts = line.split(",")
                if len(parts) < 7 or parts[2] != "A":
                    continue
                try:
                    lat = nmea_to_dd(parts[3], parts[4])
                    lon = nmea_to_dd(parts[5], parts[6].split("*")[0])
                    if lat and lon:
                        points.append({"lat": lat, "lon": lon})
                except Exception:
                    pass
        if points:
            break

    return points


@app.get("/api/report/summary")
async def get_report_summary(session: str = None):
    """Generate aggregated statistics for the report view - DISABLED for performance."""
    return {
        "error": "Report endpoint temporarily disabled - use the Explorer with filters to analyze data instead."
    }

@app.get("/api/dashboard/live")
async def get_dashboard_live():
    """Get live dashboard metrics across all sessions and devices."""
    if not DB_PATH.exists():
        return {
            "status": "db_not_found",
            "strongest_device": None,
            "busiest_session": None,
            "unique_devices": {"ble": 0, "wifi_ap": 0, "wifi_client": 0, "rf": 0, "total": 0},
            "protocol_stats": [],
            "geographic_bounds": None,
            "last_capture": None,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }

    try:
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row

            # Get strongest BLE and WiFi in one pass
            bt_strongest = db.execute("SELECT address, name, manufacturer, max_rssi_dbm, device_type FROM bt_devices WHERE max_rssi_dbm IS NOT NULL ORDER BY max_rssi_dbm DESC LIMIT 1").fetchone()
            wifi_strongest = db.execute("SELECT bssid, ssid, manufacturer, max_signal_dbm, device_type FROM wifi_aps WHERE max_signal_dbm IS NOT NULL ORDER BY max_signal_dbm DESC LIMIT 1").fetchone()

            strongest_device = None
            if bt_strongest and wifi_strongest:
                bt_rssi = bt_strongest["max_rssi_dbm"] or -200
                wifi_rssi = wifi_strongest["max_signal_dbm"] or -200
                if bt_rssi > wifi_rssi:
                    strongest_device = {"type": "ble", "address": bt_strongest["address"], "name": bt_strongest["name"], "manufacturer": bt_strongest["manufacturer"], "rssi_dbm": bt_rssi, "device_type": bt_strongest["device_type"]}
                else:
                    strongest_device = {"type": "wifi", "address": wifi_strongest["bssid"], "name": wifi_strongest["ssid"], "manufacturer": wifi_strongest["manufacturer"], "rssi_dbm": wifi_rssi, "device_type": wifi_strongest["device_type"]}
            elif bt_strongest:
                strongest_device = {"type": "ble", "address": bt_strongest["address"], "name": bt_strongest["name"], "manufacturer": bt_strongest["manufacturer"], "rssi_dbm": bt_strongest["max_rssi_dbm"], "device_type": bt_strongest["device_type"]}
            elif wifi_strongest:
                strongest_device = {"type": "wifi", "address": wifi_strongest["bssid"], "name": wifi_strongest["ssid"], "manufacturer": wifi_strongest["manufacturer"], "rssi_dbm": wifi_strongest["max_signal_dbm"], "device_type": wifi_strongest["device_type"]}

            # Get busiest session using efficient CTE approach
            session_counts = db.execute("""
                WITH session_stats AS (
                    SELECT s.session_id, s.started_at_utc,
                        (SELECT COUNT(DISTINCT bssid) FROM wifi_obs WHERE session_id = s.session_id) as wifi_count,
                        (SELECT COUNT(DISTINCT address) FROM bt_obs WHERE session_id = s.session_id) as bt_count,
                        (SELECT COUNT(DISTINCT device_id) FROM rf_obs WHERE session_id = s.session_id) as rf_count
                    FROM sessions s
                )
                SELECT session_id, started_at_utc, wifi_count, bt_count, rf_count, (wifi_count + bt_count + rf_count) as total
                FROM session_stats ORDER BY total DESC LIMIT 1
            """).fetchone()

            busiest_session = None
            if session_counts:
                busiest_session = {
                    "session_id": session_counts["session_id"],
                    "started_at_utc": session_counts["started_at_utc"],
                    "total_devices": session_counts["total"],
                    "ap_count": session_counts["wifi_count"] or 0,
                    "bt_count": session_counts["bt_count"] or 0,
                    "rf_count": session_counts["rf_count"] or 0
                }

            # Get all unique device counts in one query
            unique_counts = db.execute("""
                SELECT
                    (SELECT COUNT(DISTINCT address) FROM bt_devices) as ble_count,
                    (SELECT COUNT(DISTINCT bssid) FROM wifi_aps) as wifi_ap_count,
                    (SELECT COUNT(DISTINCT mac) FROM wifi_clients) as wifi_client_count,
                    (SELECT COUNT(DISTINCT device_id) FROM rf_devices) as rf_count
            """).fetchone()

            unique_bt = unique_counts["ble_count"] or 0
            unique_wifi_ap = unique_counts["wifi_ap_count"] or 0
            unique_wifi_client = unique_counts["wifi_client_count"] or 0
            unique_rf = unique_counts["rf_count"] or 0

            # Protocol/encryption stats
            protocol_stats = [{"type": row["encryption"], "count": row["count"]} for row in db.execute("""
                SELECT encryption, COUNT(*) as count FROM wifi_aps WHERE encryption IS NOT NULL GROUP BY encryption ORDER BY count DESC LIMIT 5
            """).fetchall()]

            # Geographic bounds
            geo_bounds = None
            geo_check = db.execute("SELECT MIN(lat) as min_lat, MAX(lat) as max_lat, MIN(lon) as min_lon, MAX(lon) as max_lon FROM wifi_obs WHERE lat IS NOT NULL AND lon IS NOT NULL").fetchone()
            if geo_check and geo_check["min_lat"] is not None:
                geo_bounds = {"min_lat": geo_check["min_lat"], "max_lat": geo_check["max_lat"], "min_lon": geo_check["min_lon"], "max_lon": geo_check["max_lon"]}

            # Last capture timestamp
            last_ts = db.execute("""SELECT MAX(ts) as latest FROM (SELECT MAX(timestamp_utc) as ts FROM bt_obs UNION ALL SELECT MAX(timestamp_utc) FROM wifi_obs UNION ALL SELECT MAX(timestamp_utc) FROM rf_obs)""").fetchone()
            last_capture_ts = last_ts["latest"] if last_ts and last_ts["latest"] else None

            return {
                "status": "ok",
                "strongest_device": strongest_device,
                "busiest_session": busiest_session,
                "unique_devices": {
                    "ble": unique_bt,
                    "wifi_ap": unique_wifi_ap,
                    "wifi_client": unique_wifi_client,
                    "rf": unique_rf,
                    "total": unique_bt + unique_wifi_ap + unique_wifi_client + unique_rf
                },
                "protocol_stats": protocol_stats,
                "geographic_bounds": geo_bounds,
                "last_capture": last_capture_ts,
                "timestamp": datetime.now(timezone.utc).isoformat()
            }
    except Exception as e:
        logging.error(f"Dashboard error: {e}")
        return {
            "status": "error",
            "error": str(e),
            "strongest_device": None,
            "busiest_session": None,
            "unique_devices": {"ble": 0, "wifi_ap": 0, "wifi_client": 0, "rf": 0, "total": 0},
            "protocol_stats": [],
            "geographic_bounds": None,
            "last_capture": None,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }

@app.get("/api/analytics")
async def get_analytics():
    """Return aggregated analytics data for dashboard visualization."""
    if not DB_PATH.exists():
        return {"error": "Database not found"}

    try:
        with sqlite3.connect(str(DB_PATH)) as db:
            db.row_factory = sqlite3.Row

            # Signal strength distributions (per table - faster than UNION)
            ble_signal = db.execute("""
                SELECT CASE WHEN max_rssi_dbm >= -50 THEN 'Strong (-50 to 0)' WHEN max_rssi_dbm >= -70 THEN 'Good (-70 to -50)' WHEN max_rssi_dbm >= -85 THEN 'Fair (-85 to -70)' ELSE 'Weak (< -85)' END as signal_range, COUNT(*) as count
                FROM bt_devices WHERE max_rssi_dbm IS NOT NULL GROUP BY signal_range ORDER BY signal_range
            """).fetchall()

            wifi_signal = db.execute("""
                SELECT CASE WHEN max_signal_dbm >= -50 THEN 'Strong (-50 to 0)' WHEN max_signal_dbm >= -70 THEN 'Good (-70 to -50)' WHEN max_signal_dbm >= -85 THEN 'Fair (-85 to -70)' ELSE 'Weak (< -85)' END as signal_range, COUNT(*) as count
                FROM wifi_aps WHERE max_signal_dbm IS NOT NULL GROUP BY signal_range ORDER BY signal_range
            """).fetchall()

            # Device type counts
            device_types = db.execute("""
                SELECT 'BLE' as device_type, COUNT(*) as count FROM bt_devices
                UNION ALL SELECT 'WiFi AP', COUNT(*) FROM wifi_aps
                UNION ALL SELECT 'WiFi Client', COUNT(*) FROM wifi_clients
                UNION ALL SELECT 'RF Device', COUNT(*) FROM rf_devices
            """).fetchall()

            # Top manufacturers (BLE only for speed)
            top_manufacturers = db.execute("""
                SELECT manufacturer, COUNT(*) as count FROM bt_devices
                WHERE manufacturer IS NOT NULL GROUP BY manufacturer ORDER BY count DESC LIMIT 10
            """).fetchall()

            # WiFi encryption distribution
            wifi_encryption = db.execute("""
                SELECT encryption, COUNT(*) as count FROM wifi_aps
                WHERE encryption IS NOT NULL GROUP BY encryption ORDER BY count DESC LIMIT 10
            """).fetchall()

            # Hourly discovery (fast version - aggregate by hour from each table)
            hourly_dict = {}

            # BLE observations by hour
            for row in db.execute("SELECT strftime('%Y-%m-%d %H:00:00', timestamp_utc) as hour, COUNT(DISTINCT address) as cnt FROM bt_obs GROUP BY hour"):
                if row["hour"] not in hourly_dict:
                    hourly_dict[row["hour"]] = {"hour": row["hour"], "ble": 0, "wifi_ap": 0, "rf": 0}
                hourly_dict[row["hour"]]["ble"] = row["cnt"] or 0

            # WiFi observations by hour
            for row in db.execute("SELECT strftime('%Y-%m-%d %H:00:00', timestamp_utc) as hour, COUNT(DISTINCT bssid) as cnt FROM wifi_obs WHERE bssid IS NOT NULL GROUP BY hour"):
                if row["hour"] not in hourly_dict:
                    hourly_dict[row["hour"]] = {"hour": row["hour"], "ble": 0, "wifi_ap": 0, "rf": 0}
                hourly_dict[row["hour"]]["wifi_ap"] = row["cnt"] or 0

            # RF observations by hour
            for row in db.execute("SELECT strftime('%Y-%m-%d %H:00:00', timestamp_utc) as hour, COUNT(DISTINCT device_id) as cnt FROM rf_obs GROUP BY hour"):
                if row["hour"] not in hourly_dict:
                    hourly_dict[row["hour"]] = {"hour": row["hour"], "ble": 0, "wifi_ap": 0, "rf": 0}
                hourly_dict[row["hour"]]["rf"] = row["cnt"] or 0

            hourly = sorted(hourly_dict.values(), key=lambda x: x["hour"])

            # Session comparison stats - counts per session
            session_ble = [row["ble_count"] for row in db.execute("""
                SELECT COUNT(DISTINCT address) as ble_count FROM bt_obs GROUP BY session_id ORDER BY session_id DESC
            """).fetchall()]

            session_wifi = [row["wifi_count"] for row in db.execute("""
                SELECT COUNT(DISTINCT bssid) as wifi_count FROM wifi_obs WHERE bssid IS NOT NULL GROUP BY session_id ORDER BY session_id DESC
            """).fetchall()]

            avg_ble = sum(session_ble) / len(session_ble) if session_ble else 0
            avg_wifi = sum(session_wifi) / len(session_wifi) if session_wifi else 0

            return {
                "signal_strength": {
                    "ble": [{"range": row["signal_range"], "count": row["count"]} for row in ble_signal],
                    "wifi": [{"range": row["signal_range"], "count": row["count"]} for row in wifi_signal]
                },
                "device_types": [{"type": row["device_type"], "count": row["count"]} for row in device_types],
                "top_manufacturers": [{"manufacturer": row["manufacturer"], "count": row["count"]} for row in top_manufacturers],
                "wifi_encryption": [{"encryption": row["encryption"], "count": row["count"]} for row in wifi_encryption],
                "hourly_discovery": [{"hour": row["hour"], "ble": row["ble"] or 0, "wifi_ap": row["wifi_ap"] or 0, "rf": row["rf"] or 0} for row in hourly],
                "session_comparison": {
                    "ble_per_session": session_ble,
                    "wifi_per_session": session_wifi,
                    "avg_ble": round(avg_ble, 1),
                    "avg_wifi": round(avg_wifi, 1)
                }
            }
    except Exception as e:
        logging.error(f"Analytics error: {e}")
        return {"error": str(e)}

@app.get("/api/storage/stats")
async def get_storage_stats():
    """Return disk usage for the database, per-session capture dirs, and the underlying filesystem."""
    capture_raw = _get_capture_raw_dir()

    result = {
        "db": {"path": str(DB_PATH), "size_bytes": 0, "exists": DB_PATH.exists()},
        "capture_dir": str(capture_raw),
        "capture_base_dir": _get_config_value("CAPTURE_BASE_DIR") or "",
        "total_capture_bytes": 0,
        "sessions": [],
        "disk": None,
    }

    if DB_PATH.exists():
        try:
            result["db"]["size_bytes"] = DB_PATH.stat().st_size
        except OSError:
            pass

    # Pull session DB counts in one query
    db_sessions: dict = {}
    if DB_PATH.exists():
        try:
            with sqlite3.connect(str(DB_PATH)) as db:
                db.row_factory = sqlite3.Row
                for row in db.execute("""
                    SELECT s.session_id, s.started_at_utc, s.ended_at_utc,
                        (SELECT COUNT(DISTINCT bssid)     FROM wifi_obs WHERE session_id = s.session_id) AS ap_count,
                        (SELECT COUNT(DISTINCT address)   FROM bt_obs   WHERE session_id = s.session_id) AS bt_count,
                        (SELECT COUNT(DISTINCT device_id) FROM rf_obs   WHERE session_id = s.session_id) AS rf_count
                    FROM sessions s ORDER BY s.started_at_utc DESC
                """).fetchall():
                    r = dict(row)
                    db_sessions[r["session_id"]] = r
        except Exception as e:
            logging.error(f"Storage stats DB error: {e}")

    sessions = []
    total_capture_bytes = 0

    # Sessions that have raw files on disk
    raw_ids: set = set()
    if capture_raw.exists():
        for d in sorted(capture_raw.iterdir(), reverse=True):
            if not d.is_dir():
                continue
            raw_ids.add(d.name)
            size = _dir_size_bytes(d)
            total_capture_bytes += size
            db_info = db_sessions.get(d.name, {})
            ap = db_info.get("ap_count") or 0
            bt = db_info.get("bt_count") or 0
            rf = db_info.get("rf_count") or 0
            started = db_info.get("started_at_utc")
            ended = db_info.get("ended_at_utc")
            duration_sec = None
            if started and ended:
                try:
                    s0 = datetime.fromisoformat(started.replace("Z", "+00:00"))
                    s1 = datetime.fromisoformat(ended.replace("Z", "+00:00"))
                    duration_sec = int((s1 - s0).total_seconds())
                except Exception:
                    pass
            sessions.append({
                "session_id": d.name,
                "size_bytes": size,
                "has_raw": True,
                "in_db": d.name in db_sessions,
                "started_at_utc": started,
                "ended_at_utc": ended,
                "ap_count": ap,
                "bt_count": bt,
                "rf_count": rf,
                "total_devices": ap + bt + rf,
                "duration_sec": duration_sec,
                "is_active": bool(started and not ended),
            })

    # DB-only sessions (raw files already gone)
    for sid, db_info in db_sessions.items():
        if sid in raw_ids:
            continue
        ap = db_info.get("ap_count") or 0
        bt = db_info.get("bt_count") or 0
        rf = db_info.get("rf_count") or 0
        started = db_info.get("started_at_utc")
        ended = db_info.get("ended_at_utc")
        duration_sec = None
        if started and ended:
            try:
                s0 = datetime.fromisoformat(started.replace("Z", "+00:00"))
                s1 = datetime.fromisoformat(ended.replace("Z", "+00:00"))
                duration_sec = int((s1 - s0).total_seconds())
            except Exception:
                pass
        sessions.append({
            "session_id": sid,
            "size_bytes": 0,
            "has_raw": False,
            "in_db": True,
            "started_at_utc": started,
            "ended_at_utc": ended,
            "ap_count": ap,
            "bt_count": bt,
            "rf_count": rf,
            "total_devices": ap + bt + rf,
            "duration_sec": duration_sec,
            "is_active": bool(started and not ended),
        })

    # Sort combined list by started_at_utc descending
    sessions.sort(key=lambda x: x.get("started_at_utc") or "", reverse=True)
    result["sessions"] = sessions
    result["total_capture_bytes"] = total_capture_bytes

    # Filesystem stats for the capture mount (or project root as fallback)
    check_path = capture_raw if capture_raw.exists() else PROJECT_ROOT
    try:
        usage = shutil.disk_usage(str(check_path))
        result["disk"] = {
            "total_bytes": usage.total,
            "used_bytes": usage.used,
            "free_bytes": usage.free,
        }
    except Exception:
        pass

    return result


@app.delete("/api/sessions/{session_id}")
async def delete_session(session_id: str):
    """Delete a session's raw files and DB records. Refuses to delete an active session."""
    _validate_session(session_id)

    capture_raw = _get_capture_raw_dir()
    session_dir = (capture_raw / session_id).resolve()

    # Path traversal guard
    if not str(session_dir).startswith(str(capture_raw.resolve())):
        raise HTTPException(status_code=400, detail="Invalid session path")

    # Refuse to delete an active (still-running) session
    manifest_path = session_dir / "manifest.json"
    if manifest_path.exists():
        try:
            with open(manifest_path) as f:
                manifest = json.load(f)
            if not manifest.get("ended_at_utc"):
                raise HTTPException(status_code=409, detail="Cannot delete an active session")
        except HTTPException:
            raise
        except Exception:
            pass

    deleted = {"db_records": False, "files": False, "errors": []}

    # Remove observation and session rows from the database
    if DB_PATH.exists():
        try:
            with sqlite3.connect(str(DB_PATH)) as db:
                db.execute("DELETE FROM bt_obs   WHERE session_id = ?", (session_id,))
                db.execute("DELETE FROM wifi_obs  WHERE session_id = ?", (session_id,))
                db.execute("DELETE FROM rf_obs    WHERE session_id = ?", (session_id,))
                db.execute("DELETE FROM sessions  WHERE session_id = ?", (session_id,))
                db.commit()
            deleted["db_records"] = True
        except Exception as e:
            deleted["errors"].append(f"DB error: {e}")

    # Remove raw capture directory
    if session_dir.exists():
        try:
            shutil.rmtree(str(session_dir))
            deleted["files"] = True
        except Exception as e:
            deleted["errors"].append(f"File error: {e}")

    status = "partial" if deleted["errors"] else "ok"
    return {"status": status, "session_id": session_id, "deleted": deleted}


@app.post("/api/storage/config")
async def update_storage_config(request: Request):
    """Write CAPTURE_BASE_DIR to wardrive.conf."""
    body = await request.json()
    new_path = str(body.get("capture_base_dir", "")).strip()

    if new_path:
        if not Path(new_path).is_absolute():
            raise HTTPException(status_code=400, detail="Path must be absolute")
        try:
            (Path(new_path) / "raw").mkdir(parents=True, exist_ok=True)
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Cannot access directory: {e}")

    if not CONFIG_PATH.exists():
        raise HTTPException(status_code=500, detail="Config file not found")

    try:
        config_text = CONFIG_PATH.read_text()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Cannot read config: {e}")

    new_line = f'CAPTURE_BASE_DIR="{new_path}"'
    if re.search(r'^CAPTURE_BASE_DIR=', config_text, re.MULTILINE):
        config_text = re.sub(r'^CAPTURE_BASE_DIR=.*$', new_line, config_text, flags=re.MULTILINE)
    else:
        config_text += f'\n{new_line}\n'

    try:
        CONFIG_PATH.write_text(config_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Cannot write config: {e}")

    return {"status": "ok", "capture_base_dir": new_path}


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """Live event stream — collector state, new devices, GPS, power events."""
    await ws_hub.serve(websocket)


@app.get("/api/collectors/sdr-mode")
async def get_sdr_mode():
    """Return current SDR mode (rtl433 or wideband)."""
    try:
        from supervisor import config as cfg
        cfg.load()
        return {"mode": cfg.get("SDR_MODE", "rtl433")}
    except Exception:
        return {"mode": "rtl433"}


@app.post("/api/collectors/sdr-mode/{mode}")
async def set_sdr_mode(mode: str):
    """Toggle RTL-SDR between rtl433 and wideband during a live drive."""
    if mode not in ("rtl433", "wideband"):
        raise HTTPException(400, "mode must be rtl433 or wideband")
    import webapp.main as _self
    registry = getattr(_self, "_registry", None)
    if registry:
        await registry.set_sdr_mode(mode)
    else:
        # Supervisor not in this process — just write config for next start
        from supervisor.registry import _rewrite_conf_value
        _rewrite_conf_value("SDR_MODE", mode)
    return {"ok": True, "mode": mode}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
